export enum MemeUploadActionType {
    MEME_UPLOADED = "MEME_UPLOADED",
    RESET_IMAGE = "RESET_IMAGE",
    START_EDIT = "START_EDIT",
    STOP_EDIT = "STOP_EDIT",
    EDITOR_REF_LOADED = "EDITOR_REF_LOADED"
}
