export enum MemeUploadActionType {
    MEME_UPLOADED = "MEME_UPLOADED",
    RESET_STATE = "RESET_STATE",
    START_EDIT = "START_EDIT",
    STOP_EDIT = "STOP_EDIT",
    EDITOR_REF_LOADED = "EDITOR_REF_LOADED",
    MEME_UPLOAD_LOADING = "MEME_UPLOAD_LOADING",
    MEME_UPLOAD_NOT_LOADING = "MEME_UPLOAD_NOT_LOADING",
    MEME_SUBMITTED = "MEME_SUBMITTED",
}
