export enum MemeUploadActionType {
    MEME_IMAGE_UPLOADED = "MEME_IMAGE_UPLOADED",
    RESET_MEME_UPLOAD_STATE = "RESET_MEME_UPLOAD_STATE",
    START_IMAGE_EDIT = "START_IMAGE_EDIT",
    STOP_IMAGE_EDIT = "STOP_IMAGE_EDIT",
    IMAGE_EDITOR_REF_LOADED = "IMAGE_EDITOR_REF_LOADED",
    MEME_UPLOAD_LOADING = "MEME_UPLOAD_LOADING",
    MEME_UPLOAD_NOT_LOADING = "MEME_UPLOAD_NOT_LOADING",
    MEME_SUBMITTED = "MEME_SUBMITTED",
    SUCCESSFULLY_SUBMITTED = "SUCCESSFULLY_SUBMITTED",
    MEME_SUBMIT_ERRORED = "MEME_SUBMIT_ERRORED"
}
