export enum AuthActionType {
    LOGIN_ERROR = "LOGIN_ERROR",
    LOGIN_SUCCESS = "LOGIN_SUCCESS",
    LOGOUT_SUCCESS = "LOGOUT_SUCCESS",
    REGISTER_ERROR = "REGISTER_ERROR",
    REGISTER_SUCCESS = "REGISTER_SUCCESS",
}
